### ISSUE TITLE
Defender ate my homework

### ISSUE THREAD

**Issue by nov3mb3r** [techBrandon/CAPs#1]
The scripts [Grant-CAPPermissions.ps1](https://github.com/techBrandon/CAPs/blob/main/Grant-CAPPermissions.ps1) and [Revoke-CAPPermissions.ps1](https://github.com/techBrandon/CAPs/blob/main/Revoke-CAPPermissions.ps1) are empty :(

**Comment by techBrandon** [comment]
Doh! I wish I had a better explaination than my own stupidity. Thanks for bringing this to my attention. I just updated those files.
